char* lines[] = {
    "FAR, FAR AWAY",
    "OVER HILL,",
    "OVER DALE,",
    "LIVED A LITTLE",
    "CHILD JUST",
    "LIKE YOU",
    "YOU: MOTHER?",
    "STEPMOTHER: OH!",
    "IT'S YOU!",
    "HAVE YOU BROUGHT",
    "THE BRUSHWOOD?",
    "YES MOTHER",
    "GOOD! NOW WILL",
    "YOU GO FETCH",
    "SOME WATER?",
    "...",
    "BUT MOTHER",
    "THE SUN IS",
    "SETTING DEEP IN",
    "THE WOODS",
    "NO!",
    "YOU WILL DO",
    "AS I ASK!",
    "...",
    "YES MOTHER",
    "YOU SET OUT",
    "TO THE WELL",
    "AND WHEN YOU",
    "REACH IT THE",
    "SUN HAS ALREADY",
    "SET",
    " ",
    "NOW YOU ARE",
    "MORE LOST THAN",
    "EVER",
    "...",
    "YOU ENTER A",
    "CLEARING AND",
    "SEE A JAR ON",
    "THE FLOOR",
    "YOU THINK FOR",
    "A SECOND AND",
    "THEN PICK IT",
    "UP",
    "OUT OF THE",
    "CORNER OF YOUR",
    "EYE YOU SEE A",
    "BRIGHT GLOW",
    " ",
    "AS YOU",
    "APPROACH YOU",
    "REALISE IT IS",
    "A SMALL BALL",
    "OF FIRE",
    " ",
    "YOU OFFER OUT",
    "THE JAR AND",
    "THE FIRE MOVES",
    "INSIDE",
    "ANOTHER BALL",
    "OF FIRE",
    " ",
    "...",
    " ",
    "INTERESTING",
    " ",
    "...",
    " ",
    "YOU PUT IT",
    "IT IN YOUR",
    "JAR",
    "YOU FIND A",
    "THIRD BALL OF",
    "FIRE AND THIS",
    "TIME IT GIVES",
    "ENOUGH LIGHT",
    "THAT YOU SPOT",
    "FOOTSTEPS",
    "LEADING OUT OF",
    "THE CLEARING",
    "FOLLOW THE",
    "FOOTSTEPS?"
};