char* lines[] = {
    "FAR, FAR AWAY",
    "OVER HILL,",
    "OVER DALE,",
    "LIVED A LITTLE",
    "CHILD JUST",
    "LIKE YOU",
    "YOU: MOTHER?",
    "STEPMOTHER: OH!",
    "IT'S YOU!",
    "HAVE YOU BROUGHT",
    "BRUSHWOOD?",
    "YES MOTHER",
    "GOOD! NOW WILL",
    "YOU GO FETCH",
    "SOME WATER?",
    "...",
    "BUT MOTHER",
    "THE SUN IS",
    "SETTING DEEP IN",
    "THE WOODS",
    "NO!",
    "YOU WILL DO",
    "AS I ASK!",
    "...",
    "YES MOTHER",
    "YOU SET OUT",
    "TO THE WELL",
    "AND WHEN YOU",
    "REACH IT THE",
    "SUN HAS ALREADY",
    "SET",
    " ",
    "NOW YOU ARE",
    "MORE LOST THAN",
    "EVER",
    "...",
    "FOOTPRINTS"
};