char* lines[] = {
    "FAR, FAR AWAY",
    "OVER HILL,",
    "OVER DALE,",
    "LIVED A LITTLE",
    "CHILD JUST",
    "LIKE YOU",
    "YOU: MOTHER?",
    "STEPMOTHER: OH!",
    "IT'S YOU!",
    "HAVE YOU BROUGHT",
    "BRUSHWOOD?",
    "YOU: YES MOTHER",
    "STEPMOTHER:",
    "GOOD! NOW WILL",
    "YOU GO FETCH",
    "SOME WATER?",
    "YOU: ...",
    "YOU: BUT MOTHER",
    "THE SUN IS",
    "SETTING DEEP IN",
    "THE WOODS",
    "STEPMOTHER: NO!",
    "YOU WILL DO",
    "AS I ASK!",
    "YOU: ...",
    "YES MOTHER",
    "YOU SET OUT",
    "TO THE WELL",
    "AND WHEN YOU",
    "REACH IT THE",
    "SUN HAS ALREADY",
    "SET",
    "NOW YOU ARE",
    "MORE LOST THAN",
    "EVER..."
};