/*

 BALL.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : Tile-count as Constant.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#include "ball.h"

/* Start of tile array. */
unsigned char ball[] =
{
  0x18,0x18,0x66,0x7E,0x42,0x76,0x8D,0xF3,
  0x81,0xFF,0x42,0x7E,0x66,0x7E,0x18,0x18
};

/* End of BALL.C */
