/*

 CRACK.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 32
   Tile set      : V:\GameJam\Tools\Tiles\check.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define crackWidth 32
#define crackHeight 32
#define crackBank 0

extern unsigned char crack[];

/* End of CRACK.H */
