/*

 MUSHROOM.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : Tile-count as Constant.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#include "mushroom.h"

/* Start of tile array. */
const unsigned char mushroom[] =
{
  0x00,0x00,0x00,0x18,0x00,0x3C,0x10,0x66,
  0x2C,0x42,0x00,0x7E,0x24,0x24,0x3C,0x3C
};

/* End of MUSHROOM.C */
