/*

 SQUARE.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : Tile-count as Constant.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#include "square.h"

/* Start of tile array. */
unsigned char SquareTile[] =
{
  0x55,0x55,0xAA,0xAA,0x55,0x55,0xAA,0xAA,
  0x55,0x55,0xAA,0xAA,0x55,0x55,0xAA,0xAA
};

/* End of SQUARE.C */
