/*

 WISP.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : Tile-count as Constant.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#include "wisp.h"

/* Start of tile array. */
unsigned char wispTile[] =
{
  0x00,0x00,0x3C,0x42,0x66,0x18,0x5A,0x3C,
  0x5A,0x3C,0x66,0x18,0x3C,0x42,0x00,0x00
};

/* End of WISP.C */
