/*

 WORLD.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 32
   Tile set      : V:\GameJam\Tools\Tiles\World.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define world_data_width 32
#define world_data_height 32
#define world_data_bank 0

#define world_tile_bank 0
#define world_tile_len 46

extern const unsigned char world_tile[];

extern const unsigned char world_data[];

/* End of WORLD.H */
