/*

 WORLDMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 32
   Tile set      : World.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 128
   Split data    : No

 This file was generated by GBMB v1.8

*/

/* Bank of tiles. */
#define world_tileBank 0

/* Start of tile array. */
extern const unsigned char world_tile[];
#define world_tile_len 46

#define world_data_width 32
#define world_data_height 32
#define world_dataBank 0

extern const unsigned char world_data[];

/* End of WORLDMAP.H */
